### ISSUE TITLE
Make panel separators visible

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4020]
The "RawTherapee" theme lacks visible separators between the panels, making finding them to resize the panels guesswork.

These ones:
![imgur-2017_08_16-13 57 03](https://user-images.githubusercontent.com/5844619/29362120-e3d5080c-828a-11e7-9617-877bb6969a3b.png)

This patch lays thin grey lines where they are, and makes them a bit darker when hovered.

```css
paned > separator {
	margin-top: 4px;
	margin-left: 4px;
	border-top: 2px solid #262626;
	border-left: 2px solid #262626;
}

paned > separator:hover {
	border-top: 2px solid #101010;
	border-left: 2px solid #101010;
}
```

Before:
![imgur-2017_08_16-14 02 25](https://user-images.githubusercontent.com/5844619/29362293-9cfb86c6-828b-11e7-9a2e-622050ecbc5f.png)

After:
![imgur-2017_08_16-14 02 30](https://user-images.githubusercontent.com/5844619/29362301-a2548cc6-828b-11e7-8041-a3b718d5f390.png)

Ideally resizing handles should appear, but for some reason they don't.

Any objections to commit?
